### ISSUE TITLE
Make app compatible with Android API 10 (2.3.3 minimun)

### ISSUE THREAD

**Issue by codestation** [codestation/henkaku-android#3]
Reduce the minSdkVersion to 10 and test if still compiles/works.

**Comment by codestation** [comment]
@julioapc16  Can you test if it works correctly? Unzip it then install the apk.

[henkaku_server-1.5_api10.apk.zip](https://github.com/codestation/henkaku-android/files/457869/henkaku_server-1.5_api10.apk.zip)

**Comment by julioapc16** [comment]
It worked perfect thank you

**Comment by codestation** [comment]
Implemented on 4472178b666b575062d459e32ba0cab6b047daa4
