### ISSUE TITLE
Update inbound?

### ISSUE THREAD

**Issue by metal-velcro** [codestation/henkaku-android#5]
Hi I was wondering if you will be updating this to the latest Vita shell? I use this application exclusively as it works better than anything else

**Comment by AweenH** [comment]
Yes...I agree with you that  it works better than anything else.Hope for Update.

**Comment by CelesteBlue-dev** [comment]
@codestation I hope too for un update. Please codestation your soft is so useful.

**Comment by codestation** [comment]
Resolved on 1c5cac882ecfcdf9550e431ca70a56302651f4be. New version published.

**Comment by CelesteBlue-dev** [comment]
Thank you very much 😚😚😚😚😚
