### ISSUE TITLE
update henkaku

### ISSUE THREAD

**Issue by tomazzz369** [codestation/henkaku-android#7]
update henkaku to latest version. since this commit there was few improvements:

(06/06/2017) Added setting options to refresh config.txt and reboot (thanks The_FloW)
(06/06/2017) Added setting options to unlink memory card and download DRM-free packages
(06/06/2017) Fixed bug where HENkaku Settings and spoofed version string do not show up
(24/06/2017) Various translation fixes (thanks to all who contributed)
(24/06/2017) Skip kernel plugin loading by holding L1 during installation (or boot if using Ensō)
(30/07/2017) Skip user plugin loading by holding L1 during application startup (skip SceShell plugins by holding L at boot using Ensō)

**Comment by codestation** [comment]
There is any reason for people to continue using this now that Ensō is out? Anyway, gonna try to update the henkaku payload before xmas (probably the last one).

**Comment by tomazzz369** [comment]
thanks

btw henkaku is not required for enso? not only for first installation, but enso don't use henkaku files or something? because enso itself its pretty small

regards

**Comment by codestation** [comment]
Currently do not have a Vita to test but recompiled henkaku, taihen and added the latest Vitashell.

When somebody confirms that it works then i will merge the feature-10.3 branch and make a release.

~~[app-release.zip](https://github.com/codestation/henkaku-android/files/1637497/app-release.zip)~~

edit: doesn't work as henkaku changed the payload generation. I am gonna stop recompiling henkaku and using the official files as-is.

Gonna try something else (involving custom dns/vpn).

**Comment by nakion** [comment]
hello i have a major problem running your latest apk (app-release.zip) on my nexus 7 (2012) wifi only device , i have cyanogenmod 11 (20141112) / android 4.4.4 , every time im trying to install the latest apk it says "error app not installed ", is there any chance you could fix that ? or maybe its on my end but i have successfully installed and running your previous version HENkaku Android 1.9 , and i would be very happy to try out your latest version "app-release.zip"  :O

**Comment by codestation** [comment]
@nakion sorry but the latest "app-release" doesn't work. I am gonna do a rewrite of the app so i can serve the original and unmodified henkaku files. No ETA.

**Comment by codestation** [comment]
Released last version with latest Henkaku and Vitashell. Just to don't keep an outdated apk.

This project is closed unless there is a reason to update again (like h-encode merged into henkaku or something like that).
