### ISSUE TITLE
1.10 mobile hotspot cannot be cracked

### ISSUE THREAD

**Issue by liuxd128** [codestation/henkaku-android#8]
Hi,Vita connect mobile hotspot, enter https://192.168.1.43:8080 prompt "not found", how to solve? thank you!

**Comment by codestation** [comment]
Hi, this project became obsolete once Enso became available. So if you are on 3.60 then just go to https://enso.henkaku.xyz/ and follow the instructions.

If you are on 3.65-3.68 then install h-encore from https://github.com/TheOfficialFloW/h-encore.
