### ISSUE TITLE
It doesn't work in psvita 2000 1.10

### ISSUE THREAD

**Issue by dante2046** [codestation/henkaku-android#9]
That's only shows not found on the psvita's browser
But other phones shows "vist this site use
…"

**Comment by codestation** [comment]
Hi, this project became obsolete once Enso became available. So if you are on 3.60 then just go to https://enso.henkaku.xyz/ and follow the instructions.

If you are on 3.65-3.68 then install h-encore from https://github.com/TheOfficialFloW/h-encore.
